name: RoomMapper
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: 17.0
packages: {}
targets:
  RoomMapper:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    settings:
      base:
        PRODUCT_NAME: RoomMapper
        PRODUCT_BUNDLE_IDENTIFIER: com.alexanderbobo.RoomMapper
        DEVELOPMENT_TEAM: 
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: 1
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
    sources:
      - path: Sources
    resources:
      - path: Assets.xcassets
    dependencies:
      - sdk: ARKit.framework
      - sdk: RealityKit.framework
schemes:
  RoomMapper:
    build:
      targets:
        RoomMapper: all
    run:
      config: Debug
    test:
      config: Debug
